### ISSUE TITLE
损失计算权重设置问题

### ISSUE THREAD

**Issue by PuNeal** [slf12/GRLModel#4]
请问代码里各个属性的权重是跟预测属性的顺序一致的吗？我根据PETA数据集按照给定的预测顺序统计出来的正样本比例跟您的代码里不一致，然而按照另一个顺序计算出来的正样本比例跟您给出的权重顺序比较一致，如下：
1、论文给定的最优预测顺序：
['personalMale', 'personalLess30', 'personalLess45', 'personalLess60', 'personalLarger60','hairLong',  'accessoryMuffler',  'accessorySunglasses', 'accessoryHat',  'accessoryNothing', 'upperBodyShortSleeve', 'upperBodyThinStripes', 'upperBodyTshirt', 'upperBodyOther', 'upperBodyVNeck', 'upperBodyLogo', 'upperBodyPlaid', 'upperBodyJacket', 'upperBodyFormal', 'upperBodyCasual', 'lowerBodyTrousers', 'lowerBodyShortSkirt', 'lowerBodyJeans', 'lowerBodyShorts',  'lowerBodyCasual', 'lowerBodyFormal', 'footwearSneakers', 'footwearLeatherShoes', 'footwearSandals', 'footwearShoes', 'carryingBackpack', 'carryingMessengerBag', 'carryingNothing', 'carryingPlasticBags', 'carryingOther']
代码里给出的权重：[0.5004, 0.3231, 0.1031, 0.0639, 0.1984, 0.1976, 0.8607, 0.8520, 0.1380, 0.1343, 0.1016, 0.0700, 0.3058, 0.2945, 0.0395, 0.2394, 0.5511, 0.2932, 0.0816, 0.7465, 0.2757, 0.0265, 0.0774, 0.0199, 0.3627, 0.0336, 0.1440, 0.0443, 0.2198, 0.0163, 0.0317, 0.5201, 0.0842, 0.4526, 0.0136]；
实际统计出来的权重：
[0.5485, 0.5009, 0.3207, 0.1049, 0.0627, 0.2348, 0.0849, 0.0305, 0.0982, 0.7497, 0.1429, 0.0169, 0.0845, 0.4534,0.0119, 0.0389, 0.0269, 0.0697, 0.1325, 0.8535, 0.5172, 0.0474, 0.3055, 0.0348, 0.8643, 0.134, 0.2149, 0.292,0.0209, 0.3695, 0.1962, 0.2975, 0.2759, 0.0771, 0.1991]
2、另一种顺序：
['personalLess30', 'personalLess45', 'personalLess60', 'personalLarger60', 'carryingBackpack', 'carryingOther', 'lowerBodyCasual', 'upperBodyCasual', 'lowerBodyFormal', 'upperBodyFormal', 'accessoryHat', 'upperBodyJacket', 'lowerBodyJeans', 'footwearLeatherShoes', 'upperBodyLogo', 'hairLong', 'personalMale', 'carryingMessengerBag', 'accessoryMuffler', 'accessoryNothing',  'carryingNothing', 'upperBodyPlaid', 'carryingPlasticBags', 'footwearSandals', 'footwearShoes', 'lowerBodyShorts', 'upperBodyShortSleeve', 'lowerBodyShortSkirt', 'footwearSneakers',  'upperBodyThinStripes',  'accessorySunglasses', 'lowerBodyTrousers', 'upperBodyTshirt', 'upperBodyOther', 'upperBodyVNeck']；
计算出的权重：
[0.4914, 0.3342, 0.1016, 0.0617, 0.1932, 0.2058, 0.8586, 0.8501, 0.1402, 0.1368, 0.1017, 0.0694, 0.3027, 0.3057, 0.0393, 0.2362, 0.5457, 0.2933, 0.0836, 0.7464, 0.2753, 0.0257, 0.0774, 0.0188, 0.3605, 0.0354, 0.1396, 0.0454, 0.2101, 0.0163, 0.0306, 0.5188, 0.0822, 0.4579, 0.0125]
按照第二种顺序统计出来的结果跟您在代码中提供的结果基本一致，我根据原始数据集生成的标签文件地址为：https://drive.google.com/drive/folders/1g2CMkGHxh7Jekt2pVcHXlFkv9kM2ldp-?usp=sharing
其中名字中含'order'的文件为按照最优预测顺序生成的标签文件，另一个为按照非最优顺序生成的标签文件，可否帮忙确认一下标签是否有误吗？谢谢。

**Comment by slf12** [comment]
这个我需要确认一下，你计算权重的公式用的哪个？




| |
桑留芳
邮箱：slf12thuss@163.com
|

签名由 网易邮箱大师 定制

在2019年08月07日 16:39，PuNeal 写道：

请问代码里各个属性的权重是跟预测属性的顺序一致的吗？我根据PETA数据集按照给定的预测顺序统计出来的正样本比例跟您的代码里不一致，然而按照另一个顺序计算出来的正样本比例跟您给出的权重顺序比较一致，如下：
1、论文给定的最优预测顺序：
['personalMale', 'personalLess30', 'personalLess45', 'personalLess60', 'personalLarger60','hairLong', 'accessoryMuffler', 'accessorySunglasses', 'accessoryHat', 'accessoryNothing', 'upperBodyShortSleeve', 'upperBodyThinStripes', 'upperBodyTshirt', 'upperBodyOther', 'upperBodyVNeck', 'upperBodyLogo', 'upperBodyPlaid', 'upperBodyJacket', 'upperBodyFormal', 'upperBodyCasual', 'lowerBodyTrousers', 'lowerBodyShortSkirt', 'lowerBodyJeans', 'lowerBodyShorts', 'lowerBodyCasual', 'lowerBodyFormal', 'footwearSneakers', 'footwearLeatherShoes', 'footwearSandals', 'footwearShoes', 'carryingBackpack', 'carryingMessengerBag', 'carryingNothing', 'carryingPlasticBags', 'carryingOther']
代码里给出的权重：[0.5004, 0.3231, 0.1031, 0.0639, 0.1984, 0.1976, 0.8607, 0.8520, 0.1380, 0.1343, 0.1016, 0.0700, 0.3058, 0.2945, 0.0395, 0.2394, 0.5511, 0.2932, 0.0816, 0.7465, 0.2757, 0.0265, 0.0774, 0.0199, 0.3627, 0.0336, 0.1440, 0.0443, 0.2198, 0.0163, 0.0317, 0.5201, 0.0842, 0.4526, 0.0136]；
实际统计出来的权重：
[0.5485, 0.5009, 0.3207, 0.1049, 0.0627, 0.2348, 0.0849, 0.0305, 0.0982, 0.7497, 0.1429, 0.0169, 0.0845, 0.4534,0.0119, 0.0389, 0.0269, 0.0697, 0.1325, 0.8535, 0.5172, 0.0474, 0.3055, 0.0348, 0.8643, 0.134, 0.2149, 0.292,0.0209, 0.3695, 0.1962, 0.2975, 0.2759, 0.0771, 0.1991]
2、另一种顺序：
['personalLess30', 'personalLess45', 'personalLess60', 'personalLarger60', 'carryingBackpack', 'carryingOther', 'lowerBodyCasual', 'upperBodyCasual', 'lowerBodyFormal', 'upperBodyFormal', 'accessoryHat', 'upperBodyJacket', 'lowerBodyJeans', 'footwearLeatherShoes', 'upperBodyLogo', 'hairLong', 'personalMale', 'carryingMessengerBag', 'accessoryMuffler', 'accessoryNothing', 'carryingNothing', 'upperBodyPlaid', 'carryingPlasticBags', 'footwearSandals', 'footwearShoes', 'lowerBodyShorts', 'upperBodyShortSleeve', 'lowerBodyShortSkirt', 'footwearSneakers', 'upperBodyThinStripes', 'accessorySunglasses', 'lowerBodyTrousers', 'upperBodyTshirt', 'upperBodyOther', 'upperBodyVNeck']；
计算出的权重：
[0.4914, 0.3342, 0.1016, 0.0617, 0.1932, 0.2058, 0.8586, 0.8501, 0.1402, 0.1368, 0.1017, 0.0694, 0.3027, 0.3057, 0.0393, 0.2362, 0.5457, 0.2933, 0.0836, 0.7464, 0.2753, 0.0257, 0.0774, 0.0188, 0.3605, 0.0354, 0.1396, 0.0454, 0.2101, 0.0163, 0.0306, 0.5188, 0.0822, 0.4579, 0.0125]
按照第二种顺序统计出来的结果跟您在代码中提供的结果基本一致，我根据原始数据集生成的标签文件地址为：https://drive.google.com/drive/folders/1g2CMkGHxh7Jekt2pVcHXlFkv9kM2ldp-，可否帮忙确认一下标签是否有误吗？谢谢。

**Comment by PuNeal** [comment]
更新一下标签地址：https://drive.google.com/drive/folders/1g2CMkGHxh7Jekt2pVcHXlFkv9kM2ldp-?usp=sharing

源代码：label_weight = [0.5004, 0.3231, 0.1031, 0.0639, 0.1984, 0.1976, 0.8607, 0.8520, 0.1380, 0.1343, 0.1016, 0.0700, 0.3058, 0.2945, 0.0395, 0.2394, 0.5511, 0.2932, 0.0816, 0.7465, 0.2757, 0.0265, 0.0774, 0.0199, 0.3627, 0.0336, 0.1440, 0.0443, 0.2198, 0.0163, 0.0317, 0.5201, 0.0842, 0.4526, 0.0136]

我理解为这里的weight均为正样本在训练集中的权重，也就是正样本数目/总训练集数目, 附上您在论文中的原话：‘where pj is the positive ratio of jth attribute in the training set.’ 
谢谢！

**Comment by slf12** [comment]
weight的计算是来自于deepmar论文，我是用它的论文的公式算的，我的论文里可能写的不严谨，抱歉




| |
桑留芳
邮箱：slf12thuss@163.com
|

签名由 网易邮箱大师 定制

在2019年08月07日 16:52，PuNeal 写道：

更新一下标签地址：https://drive.google.com/drive/folders/1g2CMkGHxh7Jekt2pVcHXlFkv9kM2ldp-?usp=sharing

源代码：label_weight = [0.5004, 0.3231, 0.1031, 0.0639, 0.1984, 0.1976, 0.8607, 0.8520, 0.1380, 0.1343, 0.1016, 0.0700, 0.3058, 0.2945, 0.0395, 0.2394, 0.5511, 0.2932, 0.0816, 0.7465, 0.2757, 0.0265, 0.0774, 0.0199, 0.3627, 0.0336, 0.1440, 0.0443, 0.2198, 0.0163, 0.0317, 0.5201, 0.0842, 0.4526, 0.0136]

我理解为这里的weight均为正样本在训练集中的权重，也就是正样本数目/总训练集数目, 附上您在论文中的原话：‘where pj is the positive ratio of jth attribute in the training set.’
谢谢！

**Comment by PuNeal** [comment]
可能我的表达不是特别清晰，给您造成了误解。先附上源代码：


label_weight = tf.convert_to_tensor(label_weight, dtype=logits.dtype.base_dtype, name='attr_label_weight')
label_weight_w = []
for i in range(one_hot_labels.get_shape()[0].value):
  label_weight_w.append(tf.exp(one_hot_labels[i] - tf.multiply( tf.sign(one_hot_labels[i]-0.5) ,label_weight)))
label_weight_w = tf.convert_to_tensor(label_weight_w, dtype=logits.dtype.base_dtype, name='attr_label_weight')

我的理解：每一个样本的每一个属性的权重都是根据正样本在训练集中的占比(也就是label_weight)计算出来的，然后再将此权重乘到每一个属性对应的损失上面。
我的问题：我按照给定的顺序统计出来的每一个属性的正样本的占比跟您在代码给出的数据不一致。关于这一点可否帮忙确认一下呢？谢谢。


________________________________
发件人: Liufang Sang <notifications@github.com>
发送时间: 2019年8月7日 8:54
收件人: slf12/GRLModel <GRLModel@noreply.github.com>
抄送: PuNeal <puheng96@outlook.com>; Author <author@noreply.github.com>
主题: Re: [slf12/GRLModel] 损失计算权重设置问题 (#4)

weight的计算是来自于deepmar论文，我是用它的论文的公式算的，我的论文里可能写的不严谨，抱歉




| |
桑留芳
邮箱：slf12thuss@163.com
|

签名由 网易邮箱大师 定制

在2019年08月07日 16:52，PuNeal 写道：

更新一下标签地址：https://drive.google.com/drive/folders/1g2CMkGHxh7Jekt2pVcHXlFkv9kM2ldp-?usp=sharing

源代码：label_weight = [0.5004, 0.3231, 0.1031, 0.0639, 0.1984, 0.1976, 0.8607, 0.8520, 0.1380, 0.1343, 0.1016, 0.0700, 0.3058, 0.2945, 0.0395, 0.2394, 0.5511, 0.2932, 0.0816, 0.7465, 0.2757, 0.0265, 0.0774, 0.0199, 0.3627, 0.0336, 0.1440, 0.0443, 0.2198, 0.0163, 0.0317, 0.5201, 0.0842, 0.4526, 0.0136]

我理解为这里的weight均为正样本在训练集中的权重，也就是正样本数目/总训练集数目, 附上您在论文中的原话：‘where pj is the positive ratio of jth attribute in the training set.’
谢谢！

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by slf12** [comment]
label weight不完全是正样本占比。。。。是根据公式算的呀。。。啥意思
| |
桑留芳
邮箱：slf12thuss@163.com
|

签名由 网易邮箱大师 定制

在2019年08月07日 17:12，PuNeal 写道：
可能我的表达不是特别清晰，给您造成了误解。先附上源代码：


label_weight = tf.convert_to_tensor(label_weight, dtype=logits.dtype.base_dtype, name='attr_label_weight')
label_weight_w = []
for i in range(one_hot_labels.get_shape()[0].value):
label_weight_w.append(tf.exp(one_hot_labels[i] - tf.multiply( tf.sign(one_hot_labels[i]-0.5) ,label_weight)))
label_weight_w = tf.convert_to_tensor(label_weight_w, dtype=logits.dtype.base_dtype, name='attr_label_weight')

我的理解：每一个样本的每一个属性的权重都是根据正样本在训练集中的占比(也就是label_weight)计算出来的，然后再将此权重乘到每一个属性对应的损失上面。
我的问题：我按照给定的顺序统计出来的每一个属性的正样本的占比跟您在代码给出的数据不一致。关于这一点可否帮忙确认一下呢？谢谢。


________________________________
发件人: Liufang Sang <notifications@github.com>
发送时间: 2019年8月7日 8:54
收件人: slf12/GRLModel <GRLModel@noreply.github.com>
抄送: PuNeal <puheng96@outlook.com>; Author <author@noreply.github.com>
主题: Re: [slf12/GRLModel] 损失计算权重设置问题 (#4)

weight的计算是来自于deepmar论文，我是用它的论文的公式算的，我的论文里可能写的不严谨，抱歉




| |
桑留芳
邮箱：slf12thuss@163.com
|

签名由 网易邮箱大师 定制

在2019年08月07日 16:52，PuNeal 写道：

更新一下标签地址：https://drive.google.com/drive/folders/1g2CMkGHxh7Jekt2pVcHXlFkv9kM2ldp-?usp=sharing

源代码：label_weight = [0.5004, 0.3231, 0.1031, 0.0639, 0.1984, 0.1976, 0.8607, 0.8520, 0.1380, 0.1343, 0.1016, 0.0700, 0.3058, 0.2945, 0.0395, 0.2394, 0.5511, 0.2932, 0.0816, 0.7465, 0.2757, 0.0265, 0.0774, 0.0199, 0.3627, 0.0336, 0.1440, 0.0443, 0.2198, 0.0163, 0.0317, 0.5201, 0.0842, 0.4526, 0.0136]

我理解为这里的weight均为正样本在训练集中的权重，也就是正样本数目/总训练集数目, 附上您在论文中的原话：‘where pj is the positive ratio of jth attribute in the training set.’
谢谢！

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by PuNeal** [comment]
Deepmar 论文中的公式：
[cid:image001.jpg@01D54D47.C9BC3830]
您发表的这篇论文中的公式：
[cid:image003.jpg@01D54D47.C9BC3830]
仔细观察这两者可以发现，二者公式并不一样，前者的权重w_l是给两项都乘了，后者只是给第一项乘了，这里是有什么特别的考虑吗？
我的问题是：根据您刚才的回答，在源代码中的label_weight这一项是根据上述公式计算出来的，那么为什么还要计算label_weight_w呢，并将label_weight_w作为计算损失时每一个属性的权重？


代码：

for i in range(one_hot_labels.get_shape()[0].value):
  label_weight_w.append(tf.exp(one_hot_labels[i] - tf.multiply( tf.sign(one_hot_labels[i]-0.5) ,label_weight)))
label_weight_w = tf.convert_to_tensor(label_weight_w, dtype=logits.dtype.base_dtype, name='attr_label_weight')
# label_weight_w = tf.exp(one_hot_labels[0] - tf.multiply( tf.sign(one_hot_labels[0]-0.5) ,label_weight))
# print(label_weight_w)

cross_entropy = tf.contrib.nn.deprecated_flipped_sigmoid_cross_entropy_with_logits(
    logits, one_hot_labels, name='xentropy')
weighted_cross_entropy = tf.multiply(cross_entropy, label_weight_w)

谢谢。

发件人: Liufang Sang [mailto:notifications@github.com]
发送时间: 2019年8月7日 17:16
收件人: slf12/GRLModel <GRLModel@noreply.github.com>
抄送: PuNeal <puheng96@outlook.com>; Author <author@noreply.github.com>
主题: Re: [slf12/GRLModel] 损失计算权重设置问题 (#4)



label weight不完全是正样本占比。。。。是根据公式算的呀。。。啥意思
| |
桑留芳
邮箱：slf12thuss@163.com<mailto:slf12thuss@163.com>
|

签名由 网易邮箱大师 定制

在2019年08月07日 17:12，PuNeal 写道：
可能我的表达不是特别清晰，给您造成了误解。先附上源代码：


label_weight = tf.convert_to_tensor(label_weight, dtype=logits.dtype.base_dtype, name='attr_label_weight')
label_weight_w = []
for i in range(one_hot_labels.get_shape()[0].value):
label_weight_w.append(tf.exp(one_hot_labels[i] - tf.multiply( tf.sign(one_hot_labels[i]-0.5) ,label_weight)))
label_weight_w = tf.convert_to_tensor(label_weight_w, dtype=logits.dtype.base_dtype, name='attr_label_weight')

我的理解：每一个样本的每一个属性的权重都是根据正样本在训练集中的占比(也就是label_weight)计算出来的，然后再将此权重乘到每一个属性对应的损失上面。
我的问题：我按照给定的顺序统计出来的每一个属性的正样本的占比跟您在代码给出的数据不一致。关于这一点可否帮忙确认一下呢？谢谢。


________________________________
发件人: Liufang Sang <notifications@github.com<mailto:notifications@github.com>>
发送时间: 2019年8月7日 8:54
收件人: slf12/GRLModel <GRLModel@noreply.github.com<mailto:GRLModel@noreply.github.com>>
抄送: PuNeal <puheng96@outlook.com<mailto:puheng96@outlook.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
主题: Re: [slf12/GRLModel] 损失计算权重设置问题 (#4)

weight的计算是来自于deepmar论文，我是用它的论文的公式算的，我的论文里可能写的不严谨，抱歉




| |
桑留芳
邮箱：slf12thuss@163.com<mailto:slf12thuss@163.com>
|

签名由 网易邮箱大师 定制

在2019年08月07日 16:52，PuNeal 写道：

更新一下标签地址：https://drive.google.com/drive/folders/1g2CMkGHxh7Jekt2pVcHXlFkv9kM2ldp-?usp=sharing

源代码：label_weight = [0.5004, 0.3231, 0.1031, 0.0639, 0.1984, 0.1976, 0.8607, 0.8520, 0.1380, 0.1343, 0.1016, 0.0700, 0.3058, 0.2945, 0.0395, 0.2394, 0.5511, 0.2932, 0.0816, 0.7465, 0.2757, 0.0265, 0.0774, 0.0199, 0.3627, 0.0336, 0.1440, 0.0443, 0.2198, 0.0163, 0.0317, 0.5201, 0.0842, 0.4526, 0.0136]

我理解为这里的weight均为正样本在训练集中的权重，也就是正样本数目/总训练集数目, 附上您在论文中的原话：‘where pj is the positive ratio of jth attribute in the training set.’
谢谢！

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by slf12** [comment]
这个是因为tf当时没有合适的weighted cross entropy loss实现，所以根据tf的实现对weight做了修改，因为不能直接将weight乘在cross entropy loss的输出上，具体公式推倒可询问论文的第一作者，另外，关于论文里公式不一致的问题，也可问第一作者，论文是他写的，我觉得是他不小心写错了




| |
桑留芳
邮箱：slf12thuss@163.com
|

签名由 网易邮箱大师 定制

在2019年08月07日 17:45，PuNeal 写道：
Deepmar 论文中的公式：
[cid:image001.jpg@01D54D47.C9BC3830]
您发表的这篇论文中的公式：
[cid:image003.jpg@01D54D47.C9BC3830]
仔细观察这两者可以发现，二者公式并不一样，前者的权重w_l是给两项都乘了，后者只是给第一项乘了，这里是有什么特别的考虑吗？
我的问题是：根据您刚才的回答，在源代码中的label_weight这一项是根据上述公式计算出来的，那么为什么还要计算label_weight_w呢，并将label_weight_w作为计算损失时每一个属性的权重？


代码：

for i in range(one_hot_labels.get_shape()[0].value):
label_weight_w.append(tf.exp(one_hot_labels[i] - tf.multiply( tf.sign(one_hot_labels[i]-0.5) ,label_weight)))
label_weight_w = tf.convert_to_tensor(label_weight_w, dtype=logits.dtype.base_dtype, name='attr_label_weight')
# label_weight_w = tf.exp(one_hot_labels[0] - tf.multiply( tf.sign(one_hot_labels[0]-0.5) ,label_weight))
# print(label_weight_w)

cross_entropy = tf.contrib.nn.deprecated_flipped_sigmoid_cross_entropy_with_logits(
logits, one_hot_labels, name='xentropy')
weighted_cross_entropy = tf.multiply(cross_entropy, label_weight_w)

谢谢。

发件人: Liufang Sang [mailto:notifications@github.com]
发送时间: 2019年8月7日 17:16
收件人: slf12/GRLModel <GRLModel@noreply.github.com>
抄送: PuNeal <puheng96@outlook.com>; Author <author@noreply.github.com>
主题: Re: [slf12/GRLModel] 损失计算权重设置问题 (#4)



label weight不完全是正样本占比。。。。是根据公式算的呀。。。啥意思
| |
桑留芳
邮箱：slf12thuss@163.com<mailto:slf12thuss@163.com>
|

签名由 网易邮箱大师 定制

在2019年08月07日 17:12，PuNeal 写道：
可能我的表达不是特别清晰，给您造成了误解。先附上源代码：


label_weight = tf.convert_to_tensor(label_weight, dtype=logits.dtype.base_dtype, name='attr_label_weight')
label_weight_w = []
for i in range(one_hot_labels.get_shape()[0].value):
label_weight_w.append(tf.exp(one_hot_labels[i] - tf.multiply( tf.sign(one_hot_labels[i]-0.5) ,label_weight)))
label_weight_w = tf.convert_to_tensor(label_weight_w, dtype=logits.dtype.base_dtype, name='attr_label_weight')

我的理解：每一个样本的每一个属性的权重都是根据正样本在训练集中的占比(也就是label_weight)计算出来的，然后再将此权重乘到每一个属性对应的损失上面。
我的问题：我按照给定的顺序统计出来的每一个属性的正样本的占比跟您在代码给出的数据不一致。关于这一点可否帮忙确认一下呢？谢谢。


________________________________
发件人: Liufang Sang <notifications@github.com<mailto:notifications@github.com>>
发送时间: 2019年8月7日 8:54
收件人: slf12/GRLModel <GRLModel@noreply.github.com<mailto:GRLModel@noreply.github.com>>
抄送: PuNeal <puheng96@outlook.com<mailto:puheng96@outlook.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
主题: Re: [slf12/GRLModel] 损失计算权重设置问题 (#4)

weight的计算是来自于deepmar论文，我是用它的论文的公式算的，我的论文里可能写的不严谨，抱歉




| |
桑留芳
邮箱：slf12thuss@163.com<mailto:slf12thuss@163.com>
|

签名由 网易邮箱大师 定制

在2019年08月07日 16:52，PuNeal 写道：

更新一下标签地址：https://drive.google.com/drive/folders/1g2CMkGHxh7Jekt2pVcHXlFkv9kM2ldp-?usp=sharing

源代码：label_weight = [0.5004, 0.3231, 0.1031, 0.0639, 0.1984, 0.1976, 0.8607, 0.8520, 0.1380, 0.1343, 0.1016, 0.0700, 0.3058, 0.2945, 0.0395, 0.2394, 0.5511, 0.2932, 0.0816, 0.7465, 0.2757, 0.0265, 0.0774, 0.0199, 0.3627, 0.0336, 0.1440, 0.0443, 0.2198, 0.0163, 0.0317, 0.5201, 0.0842, 0.4526, 0.0136]

我理解为这里的weight均为正样本在训练集中的权重，也就是正样本数目/总训练集数目, 附上您在论文中的原话：‘where pj is the positive ratio of jth attribute in the training set.’
谢谢！

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

―
